export enum State {
  WAITINGRESTAURANTCONFIRM = 'WAITINGRESTAURANTCONFIRM',

  PREPARING = 'PREPARING',

  WAITINGDELIVERERACCEPT = 'WAITINGDELIVERERACCEPT',

  PICKEDUP = 'PICKEDUP',

  ONTHEWAY = 'ONTHEWAY',

  DELIVERED = 'DELIVERED',
}
